### PR TITLE
Add utility functions

### PR DESCRIPTION
**Pull request by jswaro**
Added simple utility functions to ct_utils.h

Signed-off-by: James Swaro jswaro@cray.com

@sungeunchoi @ztiffany @hppritcha

### CODE REVIEW

**Comment by sungeunchoi** [comment]
Do you plan to use these or just thought they'd be useful?

**Comment by jswaro** [comment]
I plan to use some of them immediately. The rest are useful and have come from various projects I've worked on in the past. If we are very focused on performance, there are other macros for handling prefetching that could be useful.

**Comment by sungeunchoi** [comment]
👍

**Comment by hppritcha** [comment]
looks good

**Pull request merged**
