### PR TITLE
Add authorization key test

### PR DESCRIPTION
**Pull request by jswaro**
Adds a very basic test. It does not test transmit capability. 

Verified by debug output that it functions as expected. Prior testing with a modified random access had shown that it worked as expected with transmit capability. 

@sungeunchoi review (when possible) 
@hppritcha review and suggest improvements to configure.ac modifications (when possible)

I'll squash after Howard does his PR to this PR. 

Thanks!

### CODE REVIEW

**Review by hppritcha — CHANGES_REQUESTED** [review]
please merge my PR on this PR to pick up better configury setup.

**Comment by hppritcha** [comment]
See
https://github.com/jswaro/cray-tests/pull/1

**Review by hppritcha — APPROVED** [review]

**Comment by jswaro** [comment]
bot:retest

**Comment by hppritcha** [comment]
:+1:

**Pull request merged**
