### PR TITLE
Removing single threaded benchmark versions

### PR DESCRIPTION
**Pull request by a-abraham**
Deleted
        -rdm_bw.c
        -rdm_bw_threaded
        -rdm_latency.c

Fixes: #25 
@sungeunchoi 
Signed-off-by: Amith Abraham aabraham@cray.com

### CODE REVIEW

**Comment by sungeunchoi** [comment]
References to these benchmarks must also be removed from Makefile.am and scripts/run_cray_tests.py.

**Comment by a-abraham** [comment]
Updating the Makefile - I'm not seeing any references to these benchmarks in scripts/run_cray_tests.py

**Comment by sungeunchoi** [comment]
Oh right.  I forgot that I never put them in there.  Sorry about that.

**Comment by a-abraham** [comment]
I've updated my commit to include the changes to the Makefile

**Comment by sungeunchoi** [comment]
👍

**Pull request merged**
