### PR TITLE
performance/multi-node: Updated for FI_ADDR_STR.

### PR DESCRIPTION
**Pull request by e-harvey**
- Added '-f' flag to each test to specify use of FI_ADDR_STR.
- Python script allows user to specify GNI address format.

related to ofi-cray/libfabric#1189

Signed-off-by: Evan Harvey <eharvey@lanl.gov>

### CODE REVIEW

**Comment by e-harvey** [comment]
@sungeunchoi Now that #1212 has been merged, please review when you have time.

**Comment by sungeunchoi** [comment]
Is this change strictly necessary?  Also you would need to change the CT_FI_VERSION to be 1.5 for this to work.

Why are you checking in the random_access binary?  I'm hoping it's a mistake.

**Comment by e-harvey** [comment]
> Is this change strictly necessary? Also you would need to change the CT_FI_VERSION to be 1.5 for this to work.

No.
 
> Why are you checking in the random_access binary? I'm hoping it's a mistake.

That's a mistake.

**Comment by e-harvey** [comment]
Closing. This isn't needed.

**Pull request closed without merging**
